-- Migration: Create subscriptions table for PayFast integration
-- Date: 2026-03-20

CREATE TABLE IF NOT EXISTS public.subscriptions (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    m_payment_id TEXT UNIQUE NOT NULL, -- Merchant Payment ID (generated by us)
    pf_payment_id TEXT,                -- PayFast Payment ID (returned by PayFast)
    token TEXT,                       -- Transaction token for recurring billing
    plan_id TEXT NOT NULL,             -- 'starter', 'builder', 'catalyst'
    billing_period TEXT NOT NULL,      -- 'month', 'year'
    amount NUMERIC NOT NULL,
    currency TEXT DEFAULT 'ZAR',
    status TEXT DEFAULT 'PENDING',     -- 'PENDING', 'COMPLETE', 'CANCELLED', 'FAILED'
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable Row Level Security
ALTER TABLE public.subscriptions ENABLE ROW LEVEL SECURITY;

-- Drop existing policy if it exists
DROP POLICY IF EXISTS "Users can view own subscriptions" ON public.subscriptions;

-- Allow users to view their own subscriptions
CREATE POLICY "Users can view own subscriptions" ON public.subscriptions
    FOR SELECT TO authenticated USING (auth.uid() = user_id);

-- Add updated_at trigger
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_subscriptions_updated_at
    BEFORE UPDATE ON public.subscriptions
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();
